server:
  port: 8082

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: client-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/client/**
            - id: account-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/account/**
services:
  client:
    base-url: http://localhost:8080/api/client
  account:
    base-url: http://localhost:8081/api/account