server:
  port: 8081

spring:
  application:
    name: cuenta-service

  datasource:
    url: jdbc:postgresql://localhost:5434/cuentas_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    template:
      default-topic: quito-events
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: events-listener-group
      auto-offset-reset: earliest